#!/usr/bin/env php
<?php
/* * * *
 * * newSssSphocoaProject.phps
 * * startup SssSphocoaGenerator as cli app to make new phocoa project
 * * or replicate the current one
 * *
 * * developed and tested on a mac w OS X 10.5.x
 * *
 * * @version 20100504_151015 (CC) Luke JZ aka SwissalpS
 * * * */
error_reporting(E_ALL); // 0); //

// bootstrap
require_once(dirname(dirname(dirname(dirname(dirname(dirname(dirname(dirname(dirname(__FILE__))))))))) . DIRECTORY_SEPARATOR . 'SssS_bootstrap.inc');

// run as CLI tool
\SwissalpS\PHOCOA\Project\Generator::runCLI();

/* * * *\ newSssSphocoaProject.phps (CC) Luke JZ aka SwissalpS /* * * */
?>
