#!/usr/bin/php
<?php
/* * * *
 * * remakeTemplatedFilesWithInfoFromPlist.phps
 * * run SssSphocoaGenerator as cli task to remake all files
 * * ending with .SssStemplate and fill them with the information in the plist
 * * files passed.
 * *
 * * developed and tested on a mac w OS X 10.5.x
 * *
 * * @version 20100506_154028 (CC) Luke JZ aka SwissalpS
 * * * */
error_reporting(E_ALL); // 0); //

// add framework to include path
ini_set('include_path', '/Volumes/UNIX/ImgSrach/public/SssS:' . ini_get('include_path'));

require_once('_synergize/PHOCOA/SssSphocoaGenerator.inc');

// run as CLI tool
SssSphocoaGenerator::runCLIinPlaceReplacement();

/* * * *\ remakeTemplatedFilesWithInfoFromPlist.phps (CC) Luke JZ aka SwissalpS /* * * */
?>
