<?php
// This file generated by Propel 1.3.0-dev convert-props target
return array (
  'propel' =>
  array (
    'datasources' =>
    array (
      'basic' =>
      array (
        'classes' =>
        array (
          'Bla000MapBuilder' => 'basicPDOclasses/map/Bla000MapBuilder.php',
          'Bla000Peer' => 'basicPDOclasses/Bla000Peer.php',
          'Bla000' => 'basicPDOclasses/Bla000.php',
          'MediamapMapBuilder' => 'basicPDOclasses/map/MediamapMapBuilder.php',
          'MediamapPeer' => 'basicPDOclasses/MediamapPeer.php',
          'Mediamap' => 'basicPDOclasses/Mediamap.php',
          'NotesMapBuilder' => 'basicPDOclasses/map/NotesMapBuilder.php',
          'NotesPeer' => 'basicPDOclasses/NotesPeer.php',
          'Notes' => 'basicPDOclasses/Notes.php',
          'PermissionsMapBuilder' => 'basicPDOclasses/map/PermissionsMapBuilder.php',
          'PermissionsPeer' => 'basicPDOclasses/PermissionsPeer.php',
          'Permissions' => 'basicPDOclasses/Permissions.php',
          'PermpresetsMapBuilder' => 'basicPDOclasses/map/PermpresetsMapBuilder.php',
          'PermpresetsPeer' => 'basicPDOclasses/PermpresetsPeer.php',
          'Permpresets' => 'basicPDOclasses/Permpresets.php',
          'UsersMapBuilder' => 'basicPDOclasses/map/UsersMapBuilder.php',
          'UsersPeer' => 'basicPDOclasses/UsersPeer.php',
          'Users' => 'basicPDOclasses/Users.php',
        ),
      ),
    ),
  ),
);
